# Default MQTT listener
listener 1883 0.0.0.0

# WebSocket listener (optional)
listener 9001 0.0.0.0
protocol websockets

# Allow anonymous connections
allow_anonymous true

# Persistence
persistence true
persistence_location "C:\Users\user\OneDrive - Universiti Teknologi MARA\Documents\Github\Weather sense\"

# Log settings
log_dest file "C:\Users\user\OneDrive - Universiti Teknologi MARA\Documents\Github\Weather sense\mosquitto.log"